/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulator;
import java.util.Arrays;

/**
 *
 * @author RISHAV
 */
public class disksimulator extends javax.swing.JFrame {

   
    public disksimulator() {
        initComponents();
    }
    public static int heaP=0;
    public static int[] ioArray;
    public static int n=0;
    public static int v = 0;
    public disksimulator(int headP,int ioA[],int num,int value)
    {
        initComponents();
        heaP = headP;
        ioArray = new int[num];
        ioArray = ioA;
        n = num;
        v = value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        head = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Show Graph");
        jButton1.setActionCommand("showgraph");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        output.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        head.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
                
                switch(v){
                    case 1:
                        Scan obj1 = new Scan(heaP, ioArray);
                        int r1[] = obj1.method();
                        int r12 = obj1.method3();
                        String S1="";
                        System.out.println(r12);
                        for(int i=0;i<r1.length;i++){
                            S1 = S1 +(r1[i]+" ");
                        }
                        output.setText(S1);
                        S1 = Integer.toString(r12);
                        head.setText(S1);
                        //Graph G = new Graph(r1,r1.length);
                        graphxy g = new graphxy(r1,r1.length,"SCAN");
			//G.test(r1,r1.length,"SCAN");
                        break;
                    case 2:
                        Cscan obj2 = new Cscan(heaP, ioArray);
                        int r2[] = obj2.method();
                        int r22 = obj2.method3();
                        String S2="";
                        System.out.println(r22);
                        for(int i=0;i<r2.length;i++){
                            S2 = S2 +(r2[i]+" ");
                        }
                        output.setText(S2);
                        S2 = Integer.toString(r22);
                        head.setText(S2);
                        //Graph G1 = new Graph(r2,r2.length);
                        graphxy g1 = new graphxy(r2,r2.length,"CSCAN");
			//G1.test(r2,r2.length,"CSCAN");
                        break;
                    case 3:
                        Clook obj3 = new Clook(heaP, ioArray);
                        int r3[] = obj3.method();
                        int r32 = obj3.method3();
                        String S3="";
                        System.out.println(r32);
                        for(int i=0;i<r3.length;i++){
                            S3 = S3 +(r3[i]+" ");
                        }
                        output.setText(S3);
                        S3 = Integer.toString(r32);
                        head.setText(S3);
                        //Graph G2 = new Graph(r3,r3.length);
                        graphxy g2 = new graphxy(r3,r3.length,"CSCAN");
			//G2.test(r3, r3.length,"CLOOK");
                        break;
                    case 4:
                        FCFS obj4 = new FCFS(heaP, ioArray);
                        int r4[] = obj4.method();
                        int r42 = obj4.method3();
                
                        System.out.println(r42);
                        String S4="";
                        for(int i=0;i<r4.length;i++){
                            S4 = S4+(r4[i]+" ");
                        }
                        output.setText(S4);
                        S4 = Integer.toString(r42);
                        head.setText(S4);
                        //Graph G3 = new Graph(r4,r4.length);
                        graphxy g3 = new graphxy(r4,r4.length,"CSCAN");
			//G3.test(r4,r4.length,"FCFS");
                        break;
                    case 5:
                        SSTF obj5 = new SSTF(heaP, ioArray);
                        int r5[] = obj5.method();
                        int r52 = obj5.method3();
                
                        System.out.println(r52);
                        String S5="";
                        for(int i=0;i<r5.length;i++){
                            S5=S5+(r5[i]+" ");
                        }
                        output.setText(S5);
                        S5 = Integer.toString(r52);
                        head.setText(S5);
                        //Graph G4 = new Graph(r5,r5.length);
                        graphxy g4 = new graphxy(r5,r5.length,"SSTF");
			//G4.test(r5,r5.length,"SSTF");
                        break;
                        
                }
               
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(disksimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(disksimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(disksimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(disksimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new disksimulator().setVisible(true);
               
            }  
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField head;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables
}
